### ISSUE TITLE
Remap vim escape to a different key

### ISSUE THREAD

**Issue by winstxnhdw** [shaoruu/typehere.app#1]
Hey, I use the [Tridactyl](https://github.com/tridactyl/tridactyl) extension which hijacks the escape key for browsing with vim motions. Could you add either an option to rebind vim escape or add another key like <kbd>Pause</kbd> for handling escapes as well?

**Comment by shaoruu** [comment]
I tried to dig into how to remap vim keys in Ace Editor (the textarea library that I'm using), but seems a lot harder than expected. Maybe meanwhile you can just block typehere with Tridactyl? 

<img width="806" alt="image" src="https://github.com/shaoruu/typehere.app/assets/35216312/674c2009-d124-4d90-9514-a5dcafb02a66">
