### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by ravynhardcastle** [shaoruu/typehere.app#2]
I'm not sure if it's _meant_ to have a scrollbar, but on chrome I don't seem to see a scrollbar, no matter how much I type. Being able to quickly move to certain sections of the note is important to me for much longer notes, as I tend to remember where in the note itself was certain sections -- plus it's a fast way to move to the top or bottom. I understand I could probably use vim shortcuts for this, but I like being able to navigate with just my mouse.

**Comment by shaoruu** [comment]
Hi, sorry for the late response. I removed the scrollbars for aesthetic reasons, I'll look into ways of adding options to add back scrollbar and let you know! Mostly because it's quite a pain to do stuff CSS-related with ace editor (the editor for typehere).

**Comment by shaoruu** [comment]
Update: I have gone ahead and added scrollbars back as an option. You can open Ctrl/cmd+K menu, type in "Show Scrollbar". Let me know if this doesn't work!

**Comment by ravynhardcastle** [comment]
The scrollbar works, but I'm a little confused on how the keybind works. Ctrl+k is bound to notes search and also navigation -- it only does notes search if I click a menu button first, then press ctrl+k. Is there something else I should be doing to be prompting it to use notes search, or is this intended functionality?

**Comment by shaoruu** [comment]
Hmm, I think there might've been a MacOS only experience where since I was using Cmd+K, it can be triggered anywhere. I have removed the Ctrl+K keybinding from ace editor, let me know if it still requires unfocusing the editor before opening Ctrl+K. 

For the idea behind Cmd+K menu is it started with being a note search, but then I really wanted some quick actions too, so I added regular commands like toggling theme, importing/exporting, backing up to IndexedDb, etc. Which is why I have added the show/hide scrollbar in there, mostly to prevent more UI cluttering the main page.

**Comment by shaoruu** [comment]
To add on, I also really wanted workspaces to work in typehere, for example I have these following workspaces: personal, work, projects, brainstorm. Under each workspaces, I have different notes for different things. And to create workspaces, I could create complicated UI with drag and drop, but I eventually found out that the Cmd+K menu is perfect for creating, renaming, and moving notes around. You can now navigate between workspaces with left/right arrow keys (or Ctrl/Cmd+U/I), and move notes around by selecting it with arrow keys in the menu, and while holding Ctrl/Cmd, do left/right arrow keys. And if you want to "pin" a note to all workspaces (in other words make it show up everywhere), you can do Ctrl+H or Ctrl+G to pin it. 

Additionally, I have also been tuning the user experience of note searching. Now, if there are no notes that match in the current workspace, or if there are only 1 matching, I'd show the rest of the results (across all workspaces) below as well. You can also manually search all your notes if you add a `@` or `>` in front of your query, or just do Ctrl+Shift+K to open the menu.

Let me know if you have any other questions, I have added so many random features that I must've missed something haha

**Comment by shaoruu** [comment]
Oh yea, Ctrl+E for narrow screen (I am always on narrow screen)

**Comment by shaoruu** [comment]
Let me know if there are any other issues! Going to close this for now.
